language: elixir
sudo: false
elixir: 1.6.1
otp_release: 20.1
matrix:
  include:
    - otp_release: 17.5
      elixir: 1.0.5
script:
  - if [[ `elixir -v` = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
env:
  - MIX_ENV=test
# after_script:
#   - mix deps.get --only docs
#   - MIX_ENV=docs mix inch.report
