language: elixir
sudo: false

elixir: '1.7'
otp_release: '21.1'

stages:
  - check formatted
  - test

jobs:
  include:
    - stage: test

    - elixir: '1.3.4'
      otp_release: '18.0'

    - stage: check formatted
      script: mix format --check-formatted

notifications:
  recipients:
    - jose.valim@plataformatec.com.br
