language: elixir
sudo: false
elixir: 1.4.0
otp_release: 19.1
matrix:
  include:
    - otp_release: 17.5
      elixir: 1.0.5
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
env:
  - MIX_ENV=test
# after_script:
#   - mix deps.get --only docs
#   - MIX_ENV=docs mix inch.report
